### ISSUE TITLE
Crafting Duplication Bug

### ISSUE THREAD

**Issue by CadeEvs** [mobehun/BraveTechnology#2] opened 2016-09-11 14:24 UTC
With my Crafting Grid, Regular Crafting Table, and Tinker Table, Whenever I craft an item with any of the GUI's I get the item but the items don't get used up. I have Optifine and Item Scroller added but I turned both off and it still didn't work.

https://gyazo.com/1897354e3d27bfaf513413a4d7bca60d

**Comment by mobehun** [comment] 2016-09-11 17:30
I have absolutely no idea what causes this... Has this been happening in earlier versions too?

**Comment by CadeEvs** [comment] 2016-09-11 17:32
no, it hasnt. Only when I updated.

**Comment by mobehun** [comment] 2016-09-11 18:05
Thank you for letting me know, I'll look into it, as my time let's me. Until then try using v1.16

**Comment by mobehun** [comment] 2016-09-12 17:32
Issue fixed in the next update. Not sure what mod caused it and I don't have the time now to look for it.

**Comment by Ralathor** [comment] 2016-10-03 03:00
I'm running the 1.21 version and I'm experiencing the same problem as described above.

**Comment by mobehun** [comment] 2016-10-03 04:39
Yes. It still does exist and I can't do anything about it. The HQM devs are working on it... Probably.

**Comment by sebbasel** [comment] 2016-10-04 12:02
I was annoyed that nobody found a solution so I tried to figure out by myself.

The bug seems related to a specific task in a quest. The task causes corrupted data in saved world by saving wrong progress array (sizes don't match).
My current workaround was to remove the quest and relaunch the game (important). After that, I can craft again.
**The faulting quest is 'Ores' in 'Dead Man Walking'.**

The only thing that I don't know is why and when this particular quest creates corrupted data.

Hope it helps :)

**Comment by mobehun** [comment] 2016-10-04 16:30
I've removed the whole 'Dead Man Walking' guest-line and the dupe-bug was still there. I've changed the QDS tasks to Consume tasks in hope to fix it but that didn't work either.

**Comment by sebbasel** [comment] 2016-10-04 17:30
I crossed the fingers that you have the exact same issue than me... but no. Did you restart the game ?
Sadly, problems while saving data can be random or caused by not obvious side effect.

I am glad to help if needed. Can post/send the file 'data.json' located the folder 'hqm' in your saved world.
With that, I can compare with mine.

**Comment by mobehun** [comment] 2016-10-04 18:04
I don't have a file like that. What the hell?? 😃

**Comment by sebbasel** [comment] 2016-10-04 18:38
The path should be 'minecraft\saves\New World\hqm\data.json'

**Comment by mobehun** [comment] 2016-10-04 18:40
Ah okay. It's getting late in my time zone and university is a tiring thing so I'll post it tomorrow as soon as I can

**Comment by mobehun** [comment] 2016-10-05 05:14
This is the data.json:
http://pastebin.com/SQb7xrr5

**Comment by sebbasel** [comment] 2016-10-05 09:12
Your file is even worst ! There is several mismatches...
I will contact the devs in the hope that there is a solution.

This is list of corrupted quest progress :
Botania : Pure Daisy
Botania : Mana Lenses
Dead_Man_Walking : Ingots
Dead_Man_Walking : Fluids
Getting_Started : Eyes of Ender
Getting_Started : I AM GROUT!
Infinite_Resources : 'Builder'
Infinite_Resources : Endergenic Generator
Infinite_Resources : Energy Collector
Infinite_Resources : Anti-Matter Relay
Infinite_Resources : ProjectE
Advanced_Blood_Wizardry : Master Rituals
Advanced_Blood_Wizardry : Master Rituals
Agricultural_Expansion : Nature Essence
Agricultural_Expansion : Nether Essence
Agricultural_Expansion : Chicken Essence
Agricultural_Expansion : Rabbit Essence
Agricultural_Expansion : Steel Essence
Agricultural_Expansion : Glowstone Essence
Agricultural_Expansion : Spider Essence
Agricultural_Expansion : Earth Essence
Agricultural_Expansion : Cobalt Essence
Agricultural_Expansion : Water Essence
Agricultural_Expansion : Platinum Essence
Agricultural_Expansion : Dye Essence
Agricultural_Expansion : Pig Essence
Agricultural_Expansion : Tin Essence
Agricultural_Expansion : Lapis Essence
Agricultural_Expansion : Creeper Essence
Agricultural_Expansion : Cow Essence
Agricultural_Expansion : Electrum Essence
Agricultural_Expansion : Bronze Essence
Agricultural_Expansion : Experience Essence
Agricultural_Expansion : Manyullyn Essence
Agricultural_Expansion : Zombie Essence
Agricultural_Expansion : Redstone Essence
Agricultural_Expansion : Quartz Essence
Agricultural_Expansion : Guardian Essence
Agricultural_Expansion : Coal Essence
Agricultural_Expansion : Invar Essence
Agricultural_Expansion : Ardite Essence
Agricultural_Expansion : Zinc Essence
Agricultural_Expansion : Copper Essence
Agricultural_Expansion : Ghast Essence
Agricultural_Expansion : Alubrass Essence
Agricultural_Expansion : Brass Essence
Agricultural_Expansion : Nickel Essence
Agricultural_Expansion : Iron Essence
Agricultural_Expansion : Sheep Essence
Agricultural_Expansion : Apatite Essence
Agricultural_Expansion : Diamond Essence
Agricultural_Expansion : Emerald Essence
Agricultural_Expansion : Fire Essence
Agricultural_Expansion : Sapphire Essence
Agricultural_Expansion : Silver Essence
Agricultural_Expansion : Squid Essence
Agricultural_Expansion : Slime Essence
Agricultural_Expansion : Skeleton Essence
Agricultural_Expansion : Enderman Essence
Agricultural_Expansion : Ruby Essence
Agricultural_Expansion : Tanzanite Essence
Agricultural_Expansion : Blaze Essence
Agricultural_Expansion : Lead Essence
Agricultural_Expansion : Wither Essence
Agricultural_Expansion : Gold Essence
Blood_Magic : Just a prick of your finger
Botania : Pixie Dust
Botania : Rod of the Highlands
Botania : Vials
Botania : Pure Daisy
Botania : Runic Altar
Botania : Halo 6
Botania : Ring of Magnetization
Botania : Mana Lenses
Dead_Man_Walking : Fluids
Dead_Man_Walking : Got Wood?
Getting_Started : Meteorite
Getting_Started : Adamantite
Getting_Started : Vibranium
Getting_Started : Eyes of Ender
Getting_Started : I AM GROUT!
Getting_Started : End City
Getting_Started : Titanite
Infinite_Resources : 'Builder'
Infinite_Resources : Ender Pearl Farm
Infinite_Resources : Biodiesel
Infinite_Resources : Excavator
Infinite_Resources : Endergenic Generator
Infinite_Resources : Immersive Engineering
Infinite_Resources : Energy Collector
Infinite_Resources : Anti-Matter Relay
Infinite_Resources : ProjectE
Infinite_Resources : Diesel Generator

**Comment by mobehun** [comment] 2016-10-05 09:40
Oh God... That's Umm... Yea. I can't really say anything to it.

**Comment by sebbasel** [comment] 2016-10-05 10:44
Yeah, that's a bummer. Some of them could not be problematic...
By looking the source code of the mod, I think the quest type that work is the Detect type.
It is the only type that have specific code to prevent this issue.

A workaround for your modpack could be to change all quests by Detect tasks. Not ideal because it's clearly a bug in the code that would be fixed by the devs.

**Comment by mobehun** [comment] 2016-10-05 12:23
All right. I'll get to work, and change the quests to Detect type then update a new version. I hope that fixes it.

**Comment by mobehun** [comment] 2016-10-07 15:57
Changing the quests didn't help for me...

**Comment by mobehun** [comment] 2016-10-08 04:14
On a different note, crafting works fine in a new world. Soo... I'm not sure what that means

**Comment by sebbasel** [comment] 2016-10-08 13:05
That's the problem, you need only one save over the time with wrong data to mess up all. SO your new world is not concerned... yet.
In your changelog, I see you changed only the crafting tasks to detect tasks. From as far as I know, the issue is present in all task types except Detect, even Consume and Consume QDS. The problem is some of tasks are fluid related.
If you want I can check your 'data.json' file again (the wrong one).

A workaround looks like to be the best option because we have any kind of response from the developers.

**Comment by mobehun** [comment] 2016-10-08 15:46
Oh so ONLY the detect ones are working. At the end a point it's easier to just take out HQM... Not sure what to do without it. Any idea?

**Comment by sebbasel** [comment] 2016-10-10 12:16
Exactly just the detect tasks seem to be implemented correctly (IMHO). It is just a beta after all.
Get rid of HQM could be a short-term solution but replaced by what ? Better Questing ?
My knowledge ends here because it is now a matter of decisions from your side :)
If I was you, I would mods that I can trust to reduce the maintenance. It is hard enough to create a modpack without bugfixing obsuce internal mod source code !

In my corner, I still have corrupted data sometimes. When I can't craft, I fix the data with a dedicated script (.exe) that I wrote. I'm not it is shareable because trust issues, etc...

Good luck !

**Comment by mobehun** [comment] 2016-10-10 15:32
That's the only other option I know of. I'm going to move the quests to Better Questing with the next update and closing this issue(again).

**Closed as completed by mobehun** 2016-10-10 15:32 UTC
Labels: bug, help wanted
